DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("blog.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("me/edit/", views.profile_edit, name="profile_edit"),
    path("u/<str:username>/", views.profile_detail, name="profile_detail"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("post/<int:pk>/", views.post_detail, name="post_detail"),
    path("post/create/", views.post_create, name="post_create"),
    path("post/<int:pk>/edit", views.post_edit, name="post_edit"),
    path("post/<int:pk>/delete", views.post_delete, name="post_delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    nickname = models.CharField(max_length=50, blank=True)
    bio = models.TextField(blank=True)
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)

    def __str__(self):
        return self.nickname or self.user.username

blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="posts"
    )

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["nickname", "bio", "avatar"]

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "content"]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from blog.models import Post
from .forms import ProfileForm

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("/")
    else:
        form = UserCreationForm()
    return render(request, "accounts/register.html", {"form": form})

@login_required
def profile_edit(request):
    profile = request.user.profile
    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("accounts:profile_detail", username=request.user.username)
    else:
        form = ProfileForm(instance=profile)
    return render(request, "accounts/profile_edit.html", {"form": form})

def profile_detail(request, username):
    u = User.objects.get(username=username)
    posts = Post.objects.filter(author=u).order_by("-created_at")
    return render(request, "accounts/profile_detail.html", {"u": u, "posts": posts})

blog/views.py
from django.http import HttpResponse, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post
from .forms import PostForm

def post_list(request):
    # return HttpResponse("hello list")
    # posts = [
    #     {"id": 1, "title": "第一篇文章"},
    #     {"id": 2, "title": "蒸蚌！"},
    # ]
    posts = Post.objects.all().order_by("-created_at")
    return render(request, "blog/post_list.html", {"posts":posts})

def post_detail(request, pk: int):
    # return HttpResponse(f"hello detail: {pk}")
    # post = {
    #     "id": pk,
    #     "title": f"第{pk}篇文章",
    #     "content": "这是文章内容，之后会从数据库读取。"
    # }
    post = get_object_or_404(Post, pk=pk)
    return render(request, "blog/post_detail.html", {"post":post})

@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("blog:post_detail", pk=post.pk)

    else:
        form = PostForm()

    return render(request, "blog/post_form.html", {"form": form})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if post.author != request.user:
        return HttpResponseForbidden("你没有权限编辑这篇文章")

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect("blog:post_detail", pk=post.pk)
    else:
        form = PostForm(instance=post)

    return render(request, "blog/post_form.html", {"form": form})

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk = pk)

    if post.author != request.user:
        return HttpResponseForbidden("你没有权限删除这篇文章")

    if request.method == "POST":
        post.delete()
        return redirect("blog:post_list")

    return render(request, "blog/post_confirm_delete.html", {"post":post})

accounts/templates/accounts/login.html
{% extends "blog/base.html" %}
{% block title %}登录{% endblock %}
{% block content %}
<h2>登录</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">登录</button>
</form>
<p>没有账号？<a href="{% url 'accounts:register' %}">注册</a></p>
{% endblock %}

accounts/templates/accounts/profile_detail.html
{% extends "blog/base.html" %}
{% block title %}用户主页{% endblock %}
{% block content %}
<h2>{{ u.profile.nickname|default:u.username }}</h2>
<p>{{ u.profile.bio }}</p>

{% if u == user %}
  <p><a href="{% url 'accounts:profile_edit' %}">编辑资料</a></p>
{% endif %}

{% if u.profile.avatar %}
  <img src="{{ u.profile.avatar.url }}" alt="avatar" width="120">
{% else %}
  <p>（暂无头像）</p>
{% endif %}

<h3>他的文章</h3>
<ul>
  {% for post in posts %}
    <li><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></li>
  {% empty %}
    <li>暂无文章</li>
  {% endfor %}
</ul>
{% endblock %}

accounts/templates/accounts/profile_edit.html
{% extends "blog/base.html" %}

{% block title %}编辑个人资料{% endblock %}

{% block content %}
<h2>编辑个人资料</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        <label>昵称：</label>
        {{ form.nickname }}
    </div>

    <div>
        <label>简介：</label>
        {{ form.bio }}
    </div>

    <div>
        <label>头像：</label>
        {{ form.avatar }}
    </div>

    <button type="submit">保存修改</button>
</form>

<hr>

<p>
    <a href="{% url 'accounts:profile_detail' user.username %}">
        返回个人主页
    </a>
</p>

{% endblock %}

enctype="multipart/form-data" # 必须加，否则头像无法上传

accounts/templates/accounts/register.html
{% extends "blog/base.html" %}
{% block title %}注册{% endblock %}
{% block content %}
<h2>注册</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">注册并登录</button>
</form>
<p>已有账号？<a href="{% url 'accounts:login' %}">去登录</a></p>
{% endblock %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}我的博客{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'blog/style.css' %}">
</head>
<body>
    <header>
      <h1>我的 Django 博客</h1>
      <hr>

      <p>
        {% if user.is_authenticated %}
            你好，{{ user.username }}
            <br>
           <a href="{% url 'accounts:profile_detail' user.username %}">我的主页</a> |
           <a href="{% url 'accounts:profile_edit' %}">编辑资料</a>
           <form action="{% url 'accounts:logout' %}" method="post" style="display:inline;">
             {% csrf_token %}
             <button type="submit">退出</button>
           </form>
        {% else %}
          <a href="{% url 'accounts:login' %}">登录</a> |
          <a href="{% url 'accounts:register' %}">注册</a>
        {% endif %}
      </p>
    </header>


    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <hr>
        <p>© 2026 My Blog</p>
    </footer>
</body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}

{% block title %}确认删除{% endblock %}

{% block content %}
<h2>确认删除</h2>

<p>你确定要删除《{{ post.title }}》吗？此操作不可恢复。</p>

<form method="post">
  {% csrf_token %}
  <button type="submit">确认删除</button>
  <a href="{% url 'blog:post_detail' post.pk %}">取消</a>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block title %}文章详情{% endblock %}

{% block content %}

{% if user.is_authenticated and user == post.author %}
<p>
    <a href="{% url 'blog:post_edit' post.pk %}">编辑</a>
    |
    <a href="{% url 'blog:post_delete' post.pk %}">删除</a>
</p>
{% endif %}

<h2>{{ post.title }}</h2>

{% if post.author.profile.avatar %}
  <img src="{{ post.author.profile.avatar.url }}" width="40" style="vertical-align:middle;border-radius:50%;">
{% endif %}

<a href="{% url 'accounts:profile_detail' post.author.username %}">
  {{ post.author.profile.nickname|default:post.author.username }}
</a>

<p>
    发布于：{{ post.created_at|date:"Y-m-d H:i" }}
</p>


<p>{{ post.content }}</p>

<p>
    <a href="{% url 'blog:post_list' %}">← 返回列表</a>
</p>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}

{% block title %}写文章{% endblock %}

{% block content %}
<h2>写文章</h2>

<form method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">保存</button>
</form>

<p>
    <a href="{% url 'blog:post_list' %}">← 返回列表</a>
</p>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}文章列表{% endblock %}

{% block content %}
<p>
<a href="{% url 'blog:post_create' %}">新建文章</a>
</p>
<h2>文章列表</h2>
<ul>
    {% for post in posts %}
        <li>
            <a href="{% url 'blog:post_detail' post.id %}">
                {{ post.title }}
            </a>
        </li>
    {% empty %}
        <li>暂无文章</li>
    {% endfor %}
</ul>
{% endblock %}